# Generated by Django 2.2.24 on 2023-06-12 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20230612_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='new_building',
            field=models.BooleanField(verbose_name='Новостройка'),
        ),
    ]
