# Generated by Django 2.2.24 on 2023-06-12 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import property.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0005_auto_20230612_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='Текст жалобы')),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_complaint', to='property.Flat')),
                ('user', models.ForeignKey(on_delete=models.SET(property.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
