# Generated by Django 2.2.24 on 2023-06-13 08:19

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='owner_pure_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(null=True, blank=True, max_length=128, region=None, verbose_name='Нормализованный номер владельца'),
        ),
    ]
