# Generated by Django 2.2.24 on 2023-06-13 10:14

from django.db import migrations
import phonenumbers


def set_owner_pure_phone(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all().iterator():
        flat.owner_pure_phone = phonenumbers.format_number(
            phonenumbers.parse(
                flat.owners_phonenumber,
                'RU'),
            phonenumbers.PhoneNumberFormat.E164)
        if not phonenumbers.is_valid_number(flat.owner_pure_phone):
            flat.owner_pure_phone = None
        flat.save()


def move_backward(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all().iterator():
        flat.owner_pure_phone = ''
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20230613_1119'),
    ]

    operations = [
    migrations.RunPython(set_owner_pure_phone, move_backward),
    ]
