# Generated by Django 2.2.24 on 2023-06-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_auto_20230614_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='flat',
        ),
        migrations.AddField(
            model_name='owner',
            name='flat',
            field=models.ManyToManyField(related_name='owners', to='property.Flat', verbose_name='Квартиры в собственности'),
        ),
    ]
