# Generated by Django 2.2.24 on 2023-06-14 16:20

from django.db import migrations


def set_owner_flat(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for flat in Flat.objects.all():
        owner = Owner.objects.get_or_create(
            full_name=flat.owner,
            phone_number=flat.owners_phonenumber)
        owner[0].save()
        owner[0].flat.add(flat)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_auto_20230614_1906'),
    ]

    operations = [
    migrations.RunPython(set_owner_flat),
    ]
