# Generated by Django 2.2.24 on 2023-06-16 06:03

from django.conf import settings
from django.db import migrations, models
import property.models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_auto_20230614_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='user',
            field=models.ForeignKey(on_delete=models.SET(property.models.get_sentinel_user), related_name='complaints', to=settings.AUTH_USER_MODEL, verbose_name='Кто пожаловался'),
        ),
    ]
